// Generated by Wrangler on Mon Jul 08 2024 15:37:39 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	ENVIRONMENT: "dev";
	SESSION_SECRET: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	DISCORD_BOT_TOKEN: string;
	AUTHLINK_CLIENT_ID: string;
	AUTHLINK_CLIENT_SECRET: string;
	GUILDED_BOT_TOKEN: string;
	TOKEN_SECRET: string;
	DISCORD_SUPPORT_INVITE_CODE: string;
	KOFI_WEBHOOK_TOKEN: string;
	WRANGLER_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE: string;
	BITCOIN_ADDRESS: string;
	BOTS_ORIGIN: string;
	LEGACY_ORIGIN: string;
	MY_ORIGIN: string;
	CDN_ORIGIN: string;
	GIST_TOKEN: string;
	CDN: Fetcher;
	HYPERDRIVE: Hyperdrive;
}
